# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Flavio Ribeiro
tagline:          ''
description:      'Aeronautical Engineer, PhD Candidate'
url:              http://flavioluiz.github.io/
baseurl:          http://flavioluiz.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
